"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
\n$character
"""

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

#[git_branch]
#symbol = "TvT"
#format = '[$symbol \($branch\) ]($style)'
#style = 'cyan'

[git_branch]
symbol = "TvT"
format = '[[$symbol](#EC7FA9) \([$branch](yellow)\) ]($style)'
style = 'cyan'

[git_status]
conflicted = "|ğŸ¤¡ conflicted"
ahead = " â†‘ğŸ‰ ahead"
behind = " â†“ğŸ˜¡ behind"
diverged  = "|ğŸ¤¬ diverged"
# for space
modified  = "|ğŸ¥¹  modified"
staged    = "|ğŸ˜‹ staged"
untracked = "|ğŸ˜… untracked"
# stashed = "|ğŸ¤“stashed"
renamed = "|ğŸ«£  renamed"
deleted = "|ğŸ¤® deleted"

format = '([$all_status$ahead_behind]($style)) '
style = "cyan"

